// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "src/infrastructure/prisma/schema.prisma",
  migrations: {
    path: "src/infrastructure/prisma/migrations",
    seed: "tsx src/infrastructure/prisma/seed.ts"
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});


// export default defineConfig({
//   schema: "src/infrastructure/prisma/schema.prisma",
//   migrations: {
//     path: "src/infrastructure/prisma/migrations",
//     seed: "tsx src/infrastructure/prisma/seed.ts"
//   },
//   // engine: "classic",
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });
